import { invoke } from "@tauri-apps/api/core";
import type { AnalysisResult, AudioDevice, AudioInputDevice, CaptureInfo, CaptureNotePayload, CaptureStats, DiskInfoPayload, IntegrityResult, MonitorInfo, MotionStatusPayload, Settings, StatusPayload, TimelapseStatusPayload, VoiceStatusPayload } from "../types";

export const api = {
  getSettings: () => invoke<Settings>("get_settings"),
  updateSettings: (settings: Settings) => invoke<void>("update_settings", { settings }),
  getStatus: () => invoke<StatusPayload>("get_status"),
  updateHudStatus: (recordingKind: string) => invoke<void>("update_hud_status", { recordingKind }),
  startRecording: () => invoke<string>("start_webcam_recording"),
  stopRecording: () => invoke<string>("stop_webcam_recording"),
  startScreenRecording: () => invoke<string>("start_screen_recording"),
  stopScreenRecording: () => invoke<string>("stop_screen_recording"),
  stopAnyRecording: () => invoke<string>("stop_any_recording"),
  captureCurrent: () => invoke<string>("capture_current_screen"),
  captureAllMerged: () => invoke<string>("capture_all_screens_merged"),
  listRecentCaptures: () => invoke<CaptureInfo[]>("list_recent_captures"),
  getCaptureStats: () => invoke<CaptureStats>("get_capture_stats"),
  listCameras: () => invoke<string[]>("list_cameras"),
  listMonitors: () => invoke<MonitorInfo[]>("list_monitors"),
  openPath: (path: string) => invoke<void>("open_path", { path }),
  openUrl: (url: string) => invoke<void>("open_url", { url }),
  revealPath: (path: string) => invoke<void>("reveal_path", { path }),
  deleteCapture: (path: string) => invoke<void>("delete_capture", { path }),
  deleteTimelapseSession: (session: string) => invoke<void>("delete_timelapse_session", { session }),
  createTimelapseGif: (session: string) => invoke<string>("create_timelapse_gif", { session }),
  runAnalysis: (filePath: string | null, prompt: string) =>
    invoke<AnalysisResult>("run_defeye_analysis", { filePath, prompt }),
  testOllama: (endpoint: string) =>
    invoke<string>("test_ollama", { endpoint }),
  listOllamaModels: (endpoint: string) =>
    invoke<string[]>("list_ollama_models", { endpoint }),
  toggleMotionMode: () => invoke<boolean>("toggle_motion_mode"),
  getMotionStatus: () => invoke<MotionStatusPayload>("get_motion_status"),
  updateMotionSettings: (settings: Settings) => invoke<void>("update_motion_settings", { settings }),
  analyzeLastMotionClip: (prompt: string) =>
    invoke<AnalysisResult>("analyze_last_motion_clip", { prompt }),
  exitApp: () => invoke<void>("exit_app"),
  setSystemTrayEnabled: (enabled: boolean) => invoke<void>("set_system_tray_enabled", { enabled }),
  listAudioDevices: () => invoke<AudioDevice[]>("list_audio_devices"),
  verifyIntegrity: (path: string) => invoke<IntegrityResult>("verify_integrity", { path }),
  cycleCamera: (direction: number) => invoke<string>("cycle_camera", { direction }),
  switchScreenMonitor: (monitorId: string) => invoke<string>("switch_screen_monitor", { monitorId }),
  startCameraPreview: () => invoke<string>("start_camera_preview"),
  stopCameraPreview: () => invoke<void>("stop_camera_preview"),
  startRegionSelector: () => invoke<void>("start_region_selector"),
  closeRegionSelector: () => invoke<void>("close_region_selector"),
  toggleStealthMode: () => invoke<boolean>("toggle_stealth_mode"),
  getDiskInfo: () => invoke<DiskInfoPayload>("get_disk_info"),
  setCaptureNote: (path: string, note: string) => invoke<void>("set_capture_note", { path, note }),
  getCaptureNote: (path: string) => invoke<CaptureNotePayload>("get_capture_note", { path }),
  extractSnapshot: (videoPath: string, timestampSecs: number) => invoke<string>("extract_snapshot", { videoPath, timestampSecs }),
  startTimelapse: () => invoke<void>("start_timelapse"),
  stopTimelapse: () => invoke<void>("stop_timelapse"),
  getTimelapseStatus: () => invoke<TimelapseStatusPayload>("get_timelapse_status"),
  getRecordingDuration: () => invoke<number | null>("get_recording_duration"),
  updateHotkey: (actionId: string, newShortcut: string) =>
    invoke<void>("update_hotkey", { actionId, newShortcut }),
  resetHotkeys: () => invoke<void>("reset_hotkeys"),
  toggleVoiceControl: () => invoke<boolean>("toggle_voice_control"),
  getVoiceStatus: () => invoke<VoiceStatusPayload>("get_voice_status"),
  listAudioInputDevices: () => invoke<AudioInputDevice[]>("list_audio_input_devices"),
  startAudioLevelMonitor: (webcamDevice: string, screenDevice: string) =>
    invoke<void>("start_audio_level_monitor", { webcamDevice, screenDevice }),
  stopAudioLevelMonitor: () => invoke<void>("stop_audio_level_monitor"),
};
